apiVersion: v1
kind: Service
metadata:
  name: devops-utility-hub-svc
  labels:
    app: devops-utility-hub
spec:
  type: LoadBalancer
  selector:
    app: devops-utility-hub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

